CREATE TABLE COUNTRYGROUP (
      NAME VARCHAR(30) NOT NULL
    , COUNTRYCODE VARCHAR(3)
    , TEAMMANAGERFIRSTNAME VARCHAR(50)
    , TEAMMANAGERSECONDNAME VARCHAR(50)
    , TEAMMANAGERUSERNAME VARCHAR(20)
    , TEAMMANAGERPASSWORD VARCHAR(30)
    , PRIMARY KEY (NAME)
);

ALTER TABLE COUNTRYGROUP 
ADD CONSTRAINT UQ_COUNTRYGROUP_1 UNIQUE (teamManagerUsername);

CREATE TABLE ATTENDEE (
      USERNAME VARCHAR(30) NOT NULL
    , PASSWORD VARCHAR(30)
    , FIRSTNAME VARCHAR(50)
    , LASTNAME VARCHAR(50)
    , PRIMARY KEY (USERNAME)
);